#pragma once

#define MOTOR_1_PWM 5
#define MOTOR_1_DIR 4
#define MOTOR_2_PWM 6
#define MOTOR_2_DIR 7
#define MOTOR_3_PWM 10
#define MOTOR_3_DIR 12
#define MOTOR_4_PWM 11
#define MOTOR_4_DIR 13

#define SOLENOID_PIN 2

// #define BLUETOOTH_RX A0
// #define BLUETOOTH_TX A1

// CH1-CH6
#define FLYSKY_JOYSTICK_LEFT_X A3
#define FLYSKY_JOYSTICK_LEFT_Y A2
#define FLYSKY_JOYSTICK_RIGHT_X A0
#define FLYSKY_JOYSTICK_RIGHT_Y A1
#define FLYSKY_BUTTON_SWA A4
#define FLYSKY_BUTTON_SWD A5